Added dummy member to struct mqtt_response_pingresp. Reason: Visual C 2015: "error C2016: C requires that a struct or union has at least one member". Argument: Empty structs not allowed: https://stackoverflow.com/questions/755305/empty-structure-in-c.